### PR TITLE
master

### PR DESCRIPTION
**Pull request by wrtlbrmpft**

### CODE REVIEW

**Comment by wrtlbrmpft** [comment]
hi, thought you might be interested in some minor improvements i did to my fork of your awesome builder.

**Comment by wrtlbrmpft** [comment]
i just found a bug. please ignore this request.

**Comment by Djaa9** [comment]
Hi wrtl...  sorry I didn't see your pull request. I didn't really anticipate collaborators on this project, so I didn't have notifications configured properly. 

I would be very interested in some help on this project if you can spare some time.

**Comment by wrtlbrmpft** [comment]
FYI: Firelock Games just released their own builder: http://builder.oakandirongame.com/

**Comment by Djaa9** [comment]
Yeah I saw. Seems to be missing some stuff though - Admirals and initiative cards. And it doesn't work great on mobile. 
Hopefully it gets better.

**Pull request closed without merging**
